config/routes.rb
Rails.application.routes.draw do
  devise_for :mailsenders

  resources "contacts", only: [:new, :create]
	scope ":locale" do
	  root 'home#index'
	  get 'home/index'

	  get 'work' => 'home#work'

	  get 'about' => 'home#about'
	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	end
	root 'home#index'
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "dimmaaah@live.nl",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/mailsender.rb
class Mailsender < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_local


  def about
  	
  end

  def work
  	
  end

 private

  def set_local
   I18n.locale = params[:locale] if params[:locale].present?
  end
  def default_url_options(options = {})
  {locale: I18n.locale}
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.contact_email(@user).deliver_now
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div class="hidden">
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/home/about.html.erb
<div class="container page-content">

	<div class="row">
		<div class="intro-fleur col-md-6 col-sm-6 col-xs-12">
			<p>
				Fleur Feringa is a Stylist. She creates and produces original images for magazines and the world of advertising.
			</p>
			<p>
				From her multi-facetted background in different fields of the fashion industry she developed a great eye. Fleur’s broad vision, connected to an eccentric sense of style, lead her to fashion story telling within photography, film and commercials in addition to creating extraordinary shows, breath-taking window displays and curating exhibitions.
			</p>
			<p>
				Fleur has worked for a variety of clients such as: Adidas, Albert Heijn, Algemeen Dagblad, AVRO, Bijenkorf, BNN, Concertgebouw, Halal, ING Bank, KRO, LXRY Magazine, Milkshake Festival, Mysteryland, Nieuwe Revu, NYLON, Playboy, Quest, Quote, Redken, Spinnin’ Records, Talkies, Toni & Guy, Vice, VGZ, VPRO, Wasteland and many more.</p>
			<p>
				Furthermore she has created looks for Dutch Celebrity’s like: Christina Curry, Gaite Jansen, Geraldine Kemper, Jan Versteegh, Leco van Zadelhoff, Martin Garrix, Victoria Koblenko and many others.
			</p>
			<p>
				As a clothing consultant Fleur takes care of the wardrobes of private clients.
			</p>


			<p><%= t 'intro.p1' %></p>

			<p><%= link_to "See Work", root_path, class: "pull-right" %></p>
		</div>
		<div class="intro-fleur-pic col-md-6 col-sm-6 col-xs-12">
			<%= image_tag("fleur.jpg", class: "intro_pic") %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<!-- <div class="banner">
	<div id="my-carousel">
		<ol class="carousel-indicators">
			<li data-target = "#my-carousel" data-slide-to = "0" class = "active"></li>
			<li data-target = "#my-carousel" data-slide-to = "1"></li>
			<li data-target = "#my-carousel" data-slide-to = "2"></li>
		</ol>
		<div class="carousel-inner">
			<div class="item active">
				<img src="Work-Links-29" alt="work" class="img-responsive">
			</div>

			<div class="item">
				<img src="images/Work-Links-7" alt="work" class="img-responsive">
			</div>
			<div class="item">
				<img src="Work-Links-29" alt="work" class="img-responsive">
			</div>



			<div class="item active">
					<%= link_to image_tag("Work-Links-29.jpg", :alt => "Slide1"), {:class => "img-responsive", :alt => "Responsive image"} %> 
			</div>

			<div class="item">
					<%= link_to image_tag("Work-Links-7.jpg", :alt => "Slide1"), {:class => "img-responsive", :alt => "Responsive image"} %> 
			</div>

			<div class="item">
				<%= image_tag("Work-Links-7", class: "img-responsive") %> 
			</div>

		</div>
	</div>
	
</div> -->

<!-- <div class="container banner">
	<div class="owl-carousel">
		<div>
			<%= image_tag("Work-Links-7") %> 
		</div>
		<div>
			<%= image_tag("Work-Links-29") %> 
		</div>
	</div>
</div> -->


<!-- 
<div class="your-class">
  <div>no content</div>
  <div>more content</div>
  <div>your content</div>
</div>
 -->
<section id="bgcolor" style="background-color: black;">
	<div class="container banner">

	     <div id="mycarousel" class="carousel slide" data-ride="carousel">
	          <!-- Indicators -->
	          <ol class="carousel-indicators">
	            <li data-target="#mycarousel" data-slide-to="0" class="active"></li>
	            <li data-target="#mycarousel" data-slide-to="1"></li>
	            <li data-target="#mycarousel" data-slide-to="2"></li>
	            <li data-target="#mycarousel" data-slide-to="3"></li>
	            <li data-target="#mycarousel" data-slide-to="4"></li>
	          </ol>

	          <!-- Wrapper for slides -->
	          <div class="carousel-inner" role="listbox">
	            <div class="item active">
	              <%= image_tag("Work-Links-29", :alt => "fleur") %>
	            </div>
	            <div class="item">
	              <%= image_tag("Work-Rechts-1", :alt => "fleur") %>
	            </div>
	            <div class="item">
	              <%= image_tag("Work-Rechts-2", :alt => "fleur") %>
	            </div>
	          </div>
	</div>
</section>
<section id="about">
	<div class="container page-content">

	<div class="row">
		<div class="intro-fleur col-md-6 col-sm-6 col-xs-12">
			<p>
				Fleur Feringa is a Stylist. She creates and produces original images for magazines and the world of advertising.
			</p>
			<p>
				From her multi-facetted background in different fields of the fashion industry she developed a great eye. Fleur’s broad vision, connected to an eccentric sense of style, lead her to fashion story telling within photography, film and commercials in addition to creating extraordinary shows, breath-taking window displays and curating exhibitions.
			</p>
			<p>
				Fleur has worked for a variety of clients such as: Adidas, Albert Heijn, Algemeen Dagblad, AVRO, Bijenkorf, BNN, Concertgebouw, Halal, ING Bank, KRO, LXRY Magazine, Milkshake Festival, Mysteryland, Nieuwe Revu, NYLON, Playboy, Quest, Quote, Redken, Spinnin’ Records, Talkies, Toni & Guy, Vice, VGZ, VPRO, Wasteland and many more.</p>
			<p>
				Furthermore she has created looks for Dutch Celebrity’s like: Christina Curry, Gaite Jansen, Geraldine Kemper, Jan Versteegh, Leco van Zadelhoff, Martin Garrix, Victoria Koblenko and many others.
			</p>
			<p>
				As a clothing consultant Fleur takes care of the wardrobes of private clients.
			</p>


			<p><%= t 'intro.p1' %></p>

			<p><%= link_to "See Work", root_path, class: "pull-right" %></p>
		</div>
		<div class="intro-fleur-pic col-md-6 col-sm-6 col-xs-12">
			<%= image_tag("fleur.jpg", class: "intro_pic") %>
		</div>
	</div>
</div>
</section>
<section id="contact">
	<div class="container">

	</div>
</section>

app/views/home/work.html.erb
<div class="container-fluid">
	<h2>Portfolio</h2>

	<div class="nav-case">
		<ul class="case">
			<li>Shoot Amsterdam 4 april</li>
			<li>Queens Project</li>
			<li>Mofo's</li>
			<li>Party People</li>
		</ul>
	</div>




	<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
		<%= image_tag("fleur-1", class: "work-show-case") %> 
		<%= image_tag("fleur-2", class: "work-show-case") %> 
		<%= image_tag("fleur-3", class: "work-show-case") %> 
		<%= image_tag("fleur-4", class: "work-show-case") %> 
		<%= image_tag("fleur-5", class: "work-show-case") %> 
		<%= image_tag("fleur-6", class: "work-show-case") %> 
		<%= image_tag("fleur-7", class: "work-show-case") %> 
	</div>
	<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
		<%= image_tag("fleur-8", class: "work-show-case") %> 
		<%= image_tag("fleur-9", class: "work-show-case") %> 
		<%= image_tag("fleur-10", class: "work-show-case") %> 
		<%= image_tag("fleur-11", class: "work-show-case") %> 
		<%= image_tag("fleur-12", class: "work-show-case") %> 
		<%= image_tag("fleur-13", class: "work-show-case") %> 
		<%= image_tag("fleur-14", class: "work-show-case") %>  
	</div>
	<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
		<%= image_tag("fleur-15", class: "work-show-case") %> 
		<%= image_tag("fleur-16", class: "work-show-case") %> 
		<%= image_tag("fleur-17", class: "work-show-case") %> 
		<%= image_tag("fleur-18", class: "work-show-case") %> 
		<%= image_tag("fleur-19", class: "work-show-case") %> 
		<%= image_tag("fleur-20", class: "work-show-case") %> 
		<%= image_tag("fleur-21", class: "work-show-case") %> 
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fleur</title>

<link rel="stylesheet" type="text/css" href="slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="slick/slick-theme.css"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
  <div class="nav-bar">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= render 'shared/navbar' %>
  </div>
    <%= yield %>


  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
	<div id="navbar" class="navbar">
			<div class="container">
			<ul class="pull-right">
				<li><%= link_to "Home", root_path%></li>
				<li><%= link_to "About", about_path%></li>
				<li><%= link_to "Contact", root_path%></li>
				<li class="nav-item dropdown">
           			 <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cases</a>
           			 <div class="dropdown-menu" aria-labelledby="dropdown01">
		            	<ul>
			            	<li>
			            	<%= link_to work_path do %>
			            	<div class="li-div">
			            		<%= image_tag("fleur-11.jpg", class: "tet") do %>
			            		<p class="caseitem"><h4>Shoot Amsterdam</h4></p>
			            		<% end %>
			            	</div>
			            	<% end %>
			            	</li>
			            		<li>
			            	<%= link_to work_path do %>
			            		<p class="caseitem"><h4>Queens Party</h4></p>
			            	<div class="li-div">
			            		<%= image_tag("fleur-18.jpg", class: "tet") %>
			            	</div>
			            	<% end %>
			            	</li>
			            		<li>
			            	<%= link_to work_path do %>
			            		<p class="caseitem"><h4>Celebs</h4></p>
			            	<div class="li-div">
			            		<%= image_tag("fleur-20.jpg", class: "tet") %>
			            	</div>
			            	<% end %>
			            	</li>
			         <!--    	<li><%= link_to "Shoot Amsterdam", root_path%></li>
			            	<hr>
			            	<li><%= link_to "Queens Party", root_path%></li>
			            	<hr>
			            	<li><%= link_to "Celebs", root_path%></li> -->
						</ul>
            		</div>
          		</li>
          	</ul>

<!-- 				<li class="pull-right"><%= link_to_unless_current image_tag("uk.png"), locale: "en" %></li>
      <li class="pull-right"><%= link_to_unless_current image_tag("nl.png"), locale: "nl" %></li>  
    </ul> -->
				
		</div>
	</div>
</nav>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>